apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-3
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: cluster-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: my-greeter
    repoURL: https://pietromcp.gitlab.io/my-chart-repository
    targetRevision: 0.1.1
